// Generated by CoffeeScript 1.7.1
(function() {
  window.Gather = (function() {
    function Gather() {
      this.items = [];
    }

    Gather.prototype.addItem = function(name, amount) {
      var item;
      item = {
        name: name,
        amount: amount,
        collected: 0
      };
      return this.items.push(item);
    };

    Gather.prototype.collectItem = function(item_name) {
      var item, _i, _len, _ref;
      _ref = this.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.name === item_name && item.collected < item.amount) {
          item.collected++;
        }
      }
    };

    Gather.prototype.isComplete = function() {
      var item, _i, _len, _ref;
      _ref = this.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.collected < item.amount) {
          return false;
        }
      }
      return true;
    };

    Gather.prototype.schedule = function() {
      var checkbox, item, label, row, rows, _i, _len, _ref;
      rows = [];
      _ref = this.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        row = new Row;
        checkbox = new Checkbox;
        checkbox.complete(item.collected === item.amount);
        label = new Label("" + item.name + ":" + item.collected + "/" + item.amount);
        checkbox.appendTo(row);
        label.appendTo(row);
        rows.push(row);
      }
      return rows;
    };

    return Gather;

  })();

}).call(this);
