// Generated by CoffeeScript 1.7.1
(function() {
  window.Mission = (function() {
    function Mission(name, description) {
      this.name = name;
      this.description = description;
      this.missions = [];
    }

    Mission.prototype.add = function(mission) {
      return this.missions.push(mission);
    };

    Mission.prototype.isComplete = function() {
      var mission, _i, _len, _ref;
      _ref = this.missions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mission = _ref[_i];
        if (!mission.isComplete()) {
          return false;
        }
      }
      return true;
    };

    return Mission;

  })();

}).call(this);
