// Generated by CoffeeScript 1.7.1
(function() {
  window.Quest = (function() {
    function Quest() {
      this.monsters = [];
    }

    Quest.prototype.addMonster = function(name, amount) {
      var monster;
      monster = {
        name: name,
        amount: amount,
        killed: 0
      };
      return this.monsters.push(monster);
    };

    Quest.prototype.killMonster = function(monster_name) {
      var monster, _i, _len, _ref, _results;
      _ref = this.monsters;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        monster = _ref[_i];
        if (monster.name === monster_name && monster.killed < monster.amount) {
          _results.push(monster.killed++);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Quest.prototype.isComplete = function() {
      var monster, _i, _len, _ref;
      _ref = this.monsters;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        monster = _ref[_i];
        if (monster.killed < monster.amount) {
          return false;
        }
      }
      return true;
    };

    Quest.prototype.schedule = function() {
      var checkbox, label, monster, row, rows, _i, _len, _ref;
      rows = [];
      _ref = this.monsters;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        monster = _ref[_i];
        row = new Row;
        checkbox = new Checkbox;
        checkbox.complete(monster.amount === monster.killed);
        label = new Label("" + monster.name + ":" + monster.killed + "/" + monster.amount);
        checkbox.appendTo(row);
        label.appendTo(row);
        rows.push(row);
      }
      return rows;
    };

    return Quest;

  })();

}).call(this);
