// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Main = (function(_super) {
    __extends(Main, _super);

    function Main() {
      Main.__super__.constructor.call(this, 'main');
    }

    return Main;

  })(BaseWindow);

  window.Row = (function(_super) {
    __extends(Row, _super);

    function Row(msg, cls) {
      Row.__super__.constructor.call(this, 'row');
      if (cls != null) {
        this.addClass(cls);
      }
      if (msg != null) {
        this.setMsg(msg);
      }
    }

    return Row;

  })(BaseWindow);

  window.Options = (function(_super) {
    __extends(Options, _super);

    function Options(msg, node, that, win) {
      var option;
      this.node = node;
      Options.__super__.constructor.call(this, 'option');
      option = this;
      this.addEvent('click', function() {
        win.clearOption();
        return option.node.call(that, $(this.html).data("idx"));
      });
      if (msg != null) {
        this.setMsg(msg);
      }
    }

    return Options;

  })(BaseWindow);

  window.Checkbox = (function(_super) {
    __extends(Checkbox, _super);

    function Checkbox() {
      this.html = document.createElement('input');
      this.html.type = 'checkbox';
      this.html.disabled = 'disabled';
    }

    Checkbox.prototype.complete = function(status) {
      return this.html.checked = status;
    };

    return Checkbox;

  })(BaseWindow);

  window.Label = (function(_super) {
    __extends(Label, _super);

    function Label(msg) {
      Label.__super__.constructor.call(this, 'label');
      if (msg != null) {
        this.setMsg(msg);
      }
    }

    return Label;

  })(BaseWindow);

  window.Button = (function(_super) {
    __extends(Button, _super);

    function Button(msg) {
      Button.__super__.constructor.call(this, 'btn');
      this.addClass('submit');
      this.html.style.marginTop = "3px";
      this.html.style.marginBottom = "3px";
      this.html.style.marginLeft = "0px";
      this.setMsg(msg);
    }

    Button.prototype.addEvent = function(fn, target) {
      return Button.__super__.addEvent.call(this, 'click', fn, target);
    };

    return Button;

  })(BaseWindow);

  window.Block = (function(_super) {
    __extends(Block, _super);

    function Block(msg) {
      Block.__super__.constructor.call(this, 'block');
      this.setMsg(msg);
    }

    return Block;

  })(BaseWindow);

  window.SkillBlock = (function(_super) {
    __extends(SkillBlock, _super);

    function SkillBlock(icon, name, description, lv, maxlv) {
      SkillBlock.__super__.constructor.call(this, 'skill');
      this.setMsg("<img class='icon' src='" + icon + "'/><div class='name'>" + name + "</div><div class='lv'>" + lv + "</div><div class='maxlv'>" + maxlv + "</div><div class='description'>" + description + "</div>");
    }

    return SkillBlock;

  })(BaseWindow);

}).call(this);
