// Generated by CoffeeScript 1.7.1
(function() {
  window.WindowManager = (function() {
    function WindowManager() {
      this.windows = [];
    }

    WindowManager.prototype.addWindow = function(windows) {
      var win;
      if (!(win = this.findWindow(windows))) {
        return this.windows.push(windows);
      }
    };

    WindowManager.prototype.removeWindow = function(windows) {
      this.windows["delete"](windows);
      windows.html.remove();
      return windows = null;
    };

    WindowManager.prototype.findWindow = function(windows) {
      var index;
      index = this.windows.map(function(ele) {
        return ele.name;
      }).indexOf(windows);
      if (index !== -1) {
        return this.windows[index];
      } else {
        return false;
      }
    };

    WindowManager.prototype.getFocusWindow = function() {
      var windows, _i, _len, _ref;
      _ref = this.windows;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        windows = _ref[_i];
        if (windows.focus) {
          return windows;
        }
      }
      return false;
    };

    WindowManager.prototype.setFocusWindow = function(windows) {
      var win, _i, _len, _ref;
      _ref = this.windows;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        win = _ref[_i];
        win.focus = false;
        win.removeClass('focus');
      }
      windows = this.windows.indexOf(windows);
      this.windows[windows].focus = true;
      return this.windows[windows].addClass('focus');
    };

    WindowManager.prototype.removeFocusWindow = function() {
      var windows;
      windows = this.getFocusWindow();
      if (windows) {
        return this.removeWindow(windows);
      }
    };

    return WindowManager;

  })();

}).call(this);
