// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Collection = (function(_super) {
    __extends(Collection, _super);

    function Collection() {
      this.data = [];
    }

    Collection.prototype.get = function(key) {
      return this.data[key];
    };

    Collection.prototype.add = function(object) {
      if (this.data[object.key] != null) {
        return this.data[object.key];
      }
      if (this.data.indexOf(object.key) === -1) {
        this.data[object.key] = object;
      }
      return object;
    };

    Collection.prototype.remove = function(object) {
      var i, o, _i, _len, _ref, _results;
      _ref = this.data;
      _results = [];
      for (o = _i = 0, _len = _ref.length; _i < _len; o = ++_i) {
        i = _ref[o];
        if (o === object) {
          _results.push(this.data.splice(i, 1));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Collection.prototype.size = function() {
      return this.data.length;
    };

    Collection.prototype.clear = function() {
      return this.data = [];
    };

    return Collection;

  })(window.Base);

}).call(this);
