// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CreateRole = (function(_super) {
    __extends(CreateRole, _super);

    function CreateRole() {}

    CreateRole.prototype.initialize = function() {
      var canvas, joblabel, jobselect, namelabel, passlabel, password, rolename, submit, that, userlabel, username;
      this.win = new Windows(300, 180, "創新帳號");
      this.win.main.html.style.overflowY = "hidden";
      userlabel = $("<label>").html("帳號：");
      username = $("<input type='text' class='login-input' id='username' autocomplete='off'>");
      passlabel = $("<label>").html("密碼：");
      password = $("<input type='password' class='login-input' id='password'>");
      namelabel = $("<label>").html("角色名稱：");
      rolename = $("<input type='text' class='login-input' id='name' autocomplete='off'>").width(168);
      joblabel = $("<label>").html("職業：");
      jobselect = $("<select id='job'>").width(208).append($("<option value='Swordsman'>").html("劍士")).append($("<option value='Mage'>").html("法師")).append($("<option value='Acolyte'>").html("服侍")).append($("<option value='Thief'>").html("盜賊"));
      submit = $("<input type='submit'>").val("建立新角色");
      that = this;
      signUpFlag.win = this.win;
      submit.on('click', function() {
        return that.signUp.call(that);
      });
      $(this.win.main.html).append(userlabel).append(username).append(passlabel).append(password).append(joblabel).append(jobselect).append(namelabel).append(rolename).append(submit);
      this.background = new Image();
      this.background.src = "images/start.jpg";
      canvas = document.getElementById('__game_canvas__');
      this.ctx = canvas.getContext('2d');
      this.background.onload = function() {
        return that.ctx.drawImage(this, 0, 0);
      };
      return this.rootScene = {
        update: function() {},
        draw: function() {
          return that.ctx.drawImage(that.background, 0, 0);
        }
      };
    };

    CreateRole.prototype.signUp = function() {
      var job, password, rolename, username;
      username = $('#username').val();
      password = $('#password').val();
      rolename = $('#name').val();
      job = $('#job').val();
      if ((username != null) && (password != null) && (rolename != null)) {
        return socket.emit('SignUp', {
          username: username,
          password: password,
          name: rolename,
          job: job
        });
      }
    };

    return CreateRole;

  })(Framework.Level);

  window.createRole = new CreateRole;

}).call(this);
