// Generated by CoffeeScript 1.7.1
(function() {
  var afterLoader, loader;

  window.Loader = (function() {
    function Loader(complate) {
      this.complate = complate;
      this.list = [];
      this.index = 0;
    }

    Loader.prototype.add = function(file) {
      return this.list.push("game_sample/javascript/" + file);
    };

    Loader.prototype.start = function() {
      this.index = 0;
      return this.next();
    };

    Loader.prototype.next = function() {
      var js;
      js = document.createElement("script");
      js.type = 'text/javascript';
      js.src = this.list[this.index];
      js.file = this.list[this.index];
      js.loader = this;
      js.onload = this.afterLoadOne;
      return document.getElementsByTagName('head')[0].appendChild(js);
    };

    Loader.prototype.afterLoadOne = function() {
      this.loader.index++;
      if (this.loader.index < this.loader.list.length) {
        return this.loader.next();
      } else {
        return this.loader.complate();
      }
    };

    return Loader;

  })();

  afterLoader = function() {
    $("#login-warp").fadeOut();
    $("#game").fadeIn();
    game.init();
  };

  loader = new Loader(afterLoader);

  loader.add("jquery.js");

  loader.add("login.js");

  loader.add("base.js");

  loader.add("collection.js");

  loader.add("function.js");

  loader.add("game.js");

  loader.add("map.js");

  loader.add("animate.js");

  loader.add("sprite.js");

  loader.add("astar.js");

  loader.add("windows.js");

  loader.add("monster.js");

  loader.add("mission_quest.js");

  loader.add("mission_gather.js");

  loader.add("mission_tracing.js");

  loader.add("mission.js");

  loader.add("manager.js");

  loader.add("role.js");

  loader.add("map/prontera.js");

  loader.add("sprite/job.js");

  loader.add("sprite/monster.js");

  loader.add("npc.js");

  loader.add("npc_list.js");

  loader.add("props.js");

  loader.add("props_list.js");

  loader.start();

}).call(this);
