// Generated by CoffeeScript 1.7.1
(function() {
  window.Node = (function() {
    function Node(name, content, fn_name) {
      this.name = name;
      this.content = content;
      this.fn_name = fn_name;
      this.next = [];
      this.event = "";
    }

    Node.prototype.setContent = function(content) {
      this.content = content;
    };

    Node.prototype.addNode = function(node) {
      this.next.push(node);
      return npcMaker.redraw();
    };

    Node.prototype.addMission = function(mission) {
      this.mission = mission;
    };

    return Node;

  })();

}).call(this);
