// Generated by CoffeeScript 1.7.1
(function() {
  var NpcMaker;

  NpcMaker = (function() {
    function NpcMaker() {
      this.node = this.root = new Node('開始', '', 'start');
      this.redraw();
    }

    NpcMaker.prototype.testNode = function() {
      this.root.addNode(new Node('便當吃不飽怎麼辦？', "一個吃不飽，你不會吃兩個嗎？", "next1"));
      this.root.next[0].addNode(new Node('ANS', "真是謝謝你的高見齁", "next1_1"));
      return this.root.addNode(new Node('我做了很多事，卻得不到掌聲T^T', "乾我屁事= =", "next2"));
    };

    NpcMaker.prototype.redraw = function() {
      var ul;
      ul = this.createHtmlTree(this.root, 0);
      return $('.tree-node').html('').append(ul);
    };

    NpcMaker.prototype.createHtmlTree = function(node, layer) {
      var li, node_child, ul, _i, _len, _ref;
      ul = $('<ul>');
      li = $('<li>');
      li.html(node.name);
      li.data('node', node);
      li.on('click', this.getNode);
      li.css({
        paddingLeft: layer * 10
      });
      _ref = node.next;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        node_child = _ref[_i];
        li.append(this.createHtmlTree(node_child, layer + 1));
      }
      ul.append(li);
      return ul;
    };

    NpcMaker.prototype.createCodeTree = function() {
      var node, stack, str, tmp;
      node = this.root;
      tmp = new Date();
      str = "class NPC_" + (tmp.getTime()) + " extends window.Npc\n";
      str += "\tconstructor: (@mapname)->\n";
      str += "\t\tsuper(\"" + NPC_NAME + "\", window.job.Swordsman, @mapname, 10, 11)\n";
      stack = [];
      while (true) {
        str += this.createFunction(node);
        if (node.next.length > 0) {
          stack.push(node);
          node = node.next.pop();
        } else {
          if (stack.length > 0) {
            while (true) {
              node = stack.pop();
              if (node.next.length > 0) {
                stack.push(node);
                node = node.next.pop();
                break;
              }
              if (stack.length === 0) {
                break;
              }
            }
          }
        }
        if (stack.length === 0) {
          break;
        }
      }
      return str;
    };

    NpcMaker.prototype.setMsg = function(msg) {
      msg = msg.replace(/\n/g, "<br />");
      return "\t\t@mes \"" + msg + "\"\n";
    };

    NpcMaker.prototype.jumpNextNode = function(node) {
      return "\t\t@next @" + node.fn_name + "\n";
    };

    NpcMaker.prototype.optionNode = function(node) {
      return "\t\t@option \"" + node.name + "\", @" + node.fn_name + "\n";
    };

    NpcMaker.prototype.createFunction = function(node, name) {
      var node_child, str, _i, _len, _ref;
      str = "\t" + node.fn_name + ": ()->\n";
      str += this.setMsg(node.content);
      if (node.next.length > 1) {
        _ref = node.next;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          node_child = _ref[_i];
          str += this.optionNode(node_child);
        }
      } else if (node.next.length === 1) {
        str += this.jumpNextNode(node.next[0]);
      } else {
        str += "\t\t@next @close\n";
      }
      return str;
    };

    NpcMaker.prototype.addContent = function() {
      var content, name, that;
      that = this;
      name = $('#content-name').val();
      content = $('#content-text').val();
      that.node.next[that.node.next.length] = new Node(name, content, 0, that.node.layer + 1);
      return that.redraw();
    };

    NpcMaker.prototype.getNode = function() {
      var that;
      that = npcMaker;
      that.node = $(this).data("node");
      console.log(that.node);
      $('#content-name').val(that.node.name);
      $('#content-text').val(that.node.content);
      $('#save-content').on('click', function() {
        that.node.name = $('#content-name').val();
        that.node.content = $('#content-text').val();
        return that.redraw();
      });
      return that.redraw();
    };

    NpcMaker.prototype["export"] = function() {
      return $("#export-content").html(this.createCodeTree());
    };

    return NpcMaker;

  })();

  $(function() {
    $('.content').hide();
    $('#content-main').show();
    window.NPC_NAME = prompt("輸入NPC的名字");
    window.npcMaker = new NpcMaker();
    $('#btn-export').on('click', function() {
      $('.content').hide();
      $('#export-main').show();
      return npcMaker["export"]();
    });
    $('#btn-content').on('click', function() {
      var fn_name, name;
      name = prompt("輸入節點名稱");
      fn_name = prompt("輸入function名稱");
      window.npcMaker.node.addNode(new Node(name, "", fn_name));
      return npcMaker.redraw();
    });
    $('#btn-mission').on('click', function() {
      var name;
      name = prompt("輸入任務名稱");
      window.npcMaker.node.addMission(new Mission(name, ''));
      return npcMaker.redraw();
    });
    $(window).on('resize', function() {
      return $(".right").css({
        height: $(window).height() - $('nav').height()
      });
    });
    return $(".right").css({
      height: $(window).height() - $('nav').height()
    });
  });

}).call(this);
