// Generated by CoffeeScript 1.7.1
(function() {
  var NPC1, NPC_1398182122316, NPC_1398352070869, NPC_1398352070870, NPC_1399300918667, NPC_1399359006013,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NPC1 = (function(_super) {
    __extends(NPC1, _super);

    function NPC1(mapname) {
      this.mapname = mapname;
      NPC1.__super__.constructor.call(this, "沒有頭的戰士", window.job.Swordsman, this.mapname, 10, 11);
    }

    NPC1.prototype.start = function() {
      this.mes("你看看你身後的那棟建築物");
      return this.next(this.step2);
    };

    NPC1.prototype.step2 = function() {
      this.mes("你有發現什麼嗎？");
      this.option("有", this.yes);
      this.option("沒有", this.no);
      if (!this.mission_manager.findAllMission("新手教學")) {
        this.option("接任務", this.mis);
      }
      if (this.mission_manager.findBeingMission("新手教學")) {
        return this.option("完成教學了", this.completeMission);
      }
    };

    NPC1.prototype.yes = function() {
      this.mes("你真的有發現什麼？！");
      this.mission_manager.tracingComplete(this.name);
      return this.next(this.yes_step2);
    };

    NPC1.prototype.yes_step2 = function() {
      this.mes("我隨便講講你也認真");
      return this.next(this.close);
    };

    NPC1.prototype.no = function() {
      this.mes("唉，沒想到你竟然什麼也沒發現");
      return this.next(this.no_step2);
    };

    NPC1.prototype.no_step2 = function() {
      this.mes("看來你也不過爾爾");
      return this.next(this.close);
    };

    NPC1.prototype.mis = function() {
      var gather, quest;
      this.mission = new Mission('新手教學', '擊敗3隻瘋兔&2隻魔菇&收集兩瓶藥水');
      quest = new Quest();
      quest.addMonster("瘋兔", 3);
      quest.addMonster("魔菇", 2);
      this.mission.add(quest);
      gather = new Gather();
      gather.addItem("紅色藥水", 2);
      this.mission.add(gather);
      this.addMission(this.mission);
      this.mes("擊敗3隻瘋兔&2隻魔菇&收集兩瓶藥水，這麼簡單就算是你也應該辦的到吧");
      return this.next(this.close);
    };

    NPC1.prototype.misrandom = function() {
      var mission;
      mission = new Mission(Math.random(), Math.random());
      return this.addMission(mission);
    };

    NPC1.prototype.completeMission = function() {
      if (this.mission_manager.findBeingMission(this.mission.name).isComplete()) {
        return this.completeMissionTalk();
      } else {
        return this.beingMissionTalk();
      }
    };

    NPC1.prototype.completeMissionTalk = function() {
      this.mes("恭喜你完成任務惹");
      this.next(this.close);
      return this.mission_manager.completeMission(this.mission.name);
    };

    NPC1.prototype.beingMissionTalk = function() {
      this.mes("還沒完成任務阿，你行不行吶");
      return this.next(this.close);
    };

    return NPC1;

  })(window.Npc);

  NPC_1398182122316 = (function(_super) {
    __extends(NPC_1398182122316, _super);

    function NPC_1398182122316(mapname) {
      this.mapname = mapname;
      NPC_1398182122316.__super__.constructor.call(this, "馬囧", window.npc.npc016, this.mapname, 22, 7);
    }

    NPC_1398182122316.prototype.start = function() {
      this.mes("你好，要握個手嗎？");
      this.option("油電雙漲豪恐怖歐", this.option1);
      return this.option("薪水好少喔", this.option2);
    };

    NPC_1398182122316.prototype.option2 = function() {
      this.mes("一份薪水不夠，你可以領兩份阿？<br />像我一樣月領47萬，月存48萬才是有競爭力的表現！");
      return this.next(this.close);
    };

    NPC_1398182122316.prototype.option1 = function() {
      this.mes("我聽到你的聲音了<br />這件事情我管定了");
      return this.next(this.close);
    };

    return NPC_1398182122316;

  })(window.Npc);

  NPC_1398352070869 = (function(_super) {
    __extends(NPC_1398352070869, _super);

    function NPC_1398352070869(mapname) {
      this.mapname = mapname;
      NPC_1398352070869.__super__.constructor.call(this, "", window.npc.none, "prontera", 8, 15, 1, 1);
      game.effect.e062.show(this.map, 8, 15, 0);
    }

    NPC_1398352070869.prototype.touch = function() {
      game.role.map = game.maps.data['rock'];
      game.role.mapname = "rock";
      game.role.position = [20, 38];
      return this.close();
    };

    return NPC_1398352070869;

  })(window.Npc);

  NPC_1398352070870 = (function(_super) {
    __extends(NPC_1398352070870, _super);

    function NPC_1398352070870(mapname) {
      this.mapname = mapname;
      NPC_1398352070870.__super__.constructor.call(this, "", window.npc.none, "rock", 23, 40, 1, 1);
      game.effect.e062.show(this.map, 22, 39, 0);
    }

    NPC_1398352070870.prototype.touch = function() {
      game.role.map = game.maps.data['prontera'];
      game.role.mapname = "prontera";
      return game.role.position = [8, 13];
    };

    return NPC_1398352070870;

  })(window.Npc);

  NPC_1399300918667 = (function(_super) {
    __extends(NPC_1399300918667, _super);

    function NPC_1399300918667(mapname) {
      this.mapname = mapname;
      NPC_1399300918667.__super__.constructor.call(this, "統一", window.npc.npc017, this.mapname, 10, 11);
      this.addShopItem(new RedWater);
      this.addShopItem(new BlueWater);
    }

    NPC_1399300918667.prototype.start = function() {
      this.mes("來歐<br />不論是塑化劑，滑石粉<br />什麼樣的東西都買的到喔<br />保證便宜捏！");
      return this.next(this.openShop);
    };

    NPC_1399300918667.prototype.openShop = function() {
      this.viewShop();
      return this.next(this.close);
    };

    return NPC_1399300918667;

  })(window.Npc);

  NPC_1399359006013 = (function(_super) {
    __extends(NPC_1399359006013, _super);

    function NPC_1399359006013(mapname) {
      this.mapname = mapname;
      NPC_1399359006013.__super__.constructor.call(this, "阿雞絲", window.npc.npc069, this.mapname, 30, 5);
    }

    NPC_1399359006013.prototype.start = function() {
      this.mes("找我阿雞絲有什麼速ㄇ");
      this.option("想學怎麼煮味噌湯", this.cookShup);
      return this.option("沒事", this.nothing);
    };

    NPC_1399359006013.prototype.nothing = function() {
      this.mes("年輕人不要無所事事<br />趁現在還年輕，好好充實自己<br />想想我當初年輕的時候啊.....");
      return this.next(this.close);
    };

    NPC_1399359006013.prototype.cookShup = function() {
      this.mes("想學怎麼煮味噌湯？<br />哼哼你可真問對人了<br />讓我阿雞絲告訴你個訣竅兒");
      return this.next(this.shup);
    };

    NPC_1399359006013.prototype.shup = function() {
      this.mes("我煮味噌湯都不加味噌與豆腐der<br />改放菜頭排骨酥用肉燥提味<br />又清又香，但就略油");
      return this.next(this.res);
    };

    NPC_1399359006013.prototype.res = function() {
      this.mes("這還是味噌湯嗎？<br />感覺是菜頭湯阿...");
      return this.next(this.nonono);
    };

    NPC_1399359006013.prototype.nonono = function() {
      this.mes("不不不，這不是菜頭湯<br /><br />這味噌湯呢<br />喝起來跟排骨酥湯90%口感很像");
      return this.next(this.close);
    };

    return NPC_1399359006013;

  })(window.Npc);

  window.npcCreate = function() {
    new NPC1("rock");
    new NPC_1398182122316("rock");
    new NPC_1398352070869("prontera");
    new NPC_1398352070870("prontera");
    new NPC_1399300918667("rock");
    return new NPC_1399359006013("rock");
  };

}).call(this);
