// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Props = (function(_super) {
    __extends(Props, _super);

    function Props(name, icon, description, price) {
      this.name = name;
      this.icon = icon;
      this.description = description;
      this.price = price;
      this.sprite = new Sprite("images/" + this.icon);
    }

    Props.prototype.showBuyAmount = function() {
      var buy, cancel, label, text, that, win;
      that = this;
      win = new Windows(300, 60, "購買");
      win.main.html.style.overflowY = "hidden";
      label = $("<label>").html("數量：");
      text = $("<input type='number' class='login-input' id='amount' autofocus>").val(1);
      buy = new Button("購買");
      cancel = new Button("取消");
      cancel.addEvent(win.close, win);
      buy.html.addEventListener('click', function() {
        if (!that.buy.call(that, text.val())) {

        } else {

        }
        return win.close();
      }, false);
      $(win.main.html).append(label).append(text);
      cancel.appendTo(win.footer);
      return buy.appendTo(win.footer);
    };

    Props.prototype.buy = function(number) {
      var i, _i;
      console.log(game.role.money, number * this.price);
      if ((game.role.money - (number * this.price)) < 0) {
        return false;
      }
      game.role.money -= number * this.price;
      for (i = _i = 1; 1 <= number ? _i <= number : _i >= number; i = 1 <= number ? ++_i : --_i) {
        game.role.item_manager.addItem(this);
      }
      return true;
    };

    return Props;

  })(window.Base);

  window.RedWater = (function(_super) {
    __extends(RedWater, _super);

    function RedWater() {
      RedWater.__super__.constructor.call(this, "紅色藥水", "props/red_water.png", "補30滴血", 100);
    }

    RedWater.prototype.use = function() {
      return game.role.heal(30);
    };

    return RedWater;

  })(window.Props);

  window.Power = (function(_super) {
    __extends(Power, _super);

    function Power() {
      Power.__super__.constructor.call(this, "藥劑", "props/hp_plus.png", "增加體力10點，持續5秒", 100);
    }

    Power.prototype.use = function() {
      return game.status.s003.use(game.role, 5000);
    };

    return Power;

  })(window.Props);

  window.BlueWater = (function(_super) {
    __extends(BlueWater, _super);

    function BlueWater() {
      BlueWater.__super__.constructor.call(this, "藍色藥水", "props/blue_water.png", "每秒回5魔力，持續5秒", 100);
    }

    BlueWater.prototype.use = function() {
      return game.status.s004.use(game.role, 5000);
    };

    return BlueWater;

  })(window.Props);

}).call(this);
