// Generated by CoffeeScript 1.7.1
(function() {
  var status,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  status = (function(_super) {
    __extends(status, _super);

    function status(name, id, icon, fn) {
      this.name = name;
      this.id = id;
      this.fn = fn;
      this.icon = new Sprite(icon);
    }

    status.prototype.use = function(self, time, arg) {
      var o, _i, _len, _ref;
      if (arg == null) {
        arg = 0;
      }
      _ref = self.statusList;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        o = _ref[_i];
        if (o[0].id === this.id) {
          o[2] = new Date().getTime();
          o[3] = arg;
          return;
        }
      }
      self.statusList.push([this, time, new Date().getTime(), arg]);
      return self.calculate();
    };

    return status;

  })(window.Base);

  game.status = {};

  game.status.s001 = new status("加速術", 1, "images/status/agiup.png", function(self, arg) {
    return self.speed -= 50 + 10 * arg;
  });

  game.status.s002 = new status("回血加速", 2, "images/status/healup.png", function(self) {
    return self.recoverHP += 5;
  });

  game.status.s003 = new status("血量增加", 3, "images/status/hpup.png", function(self) {
    return self.maxHP += 20;
  });

  game.status.s004 = new status("回魔加速", 4, "", function(self) {
    return self.recoverMP += 5;
  });

  game.status.s005 = new status("緩速術", 5, "", function(self) {
    return self.speed += 70;
  });

  game.status.s006 = new status("天使之障壁", 6, "images/icon/al_angelus.png", function(self, arg) {
    return self.def += arg * 3;
  });

  game.status.s007 = new status("天使之賜福", 7, "images/icon/al_blessing.png", function(self, arg) {
    self.atk += arg;
    self.hit += arg;
    self.flee += arg;
    return self.maxHP += arg;
  });

  game.status.s008 = new status("反射盾", 8, "images/icon/cr_reflectshield.png", function(self, arg) {});

}).call(this);
